import type { NextPage } from 'next'
import Head from 'next/head'
import styled from 'styled-components'

import { Button } from '../components'

const HelloWorld = styled.div`
  color: red;
`

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>kukkubukku</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <HelloWorld>Hello Kukkubukku!</HelloWorld>
      </main>
    </div>
  )
}

export default Home
