// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-nocheck

import { Header } from '../Header'
import { Footer } from '../Footer'
import { Main, Layout } from './styles'
import Head from 'next/head'
import { GlobalStyles } from 'styles/globalStyles'
import { useTheme } from 'utils/hooks/useTheme'
import { useRouter } from 'next/router'
import { useAuth } from 'services/auth'
import { useEffect } from 'react'

interface Props {
  children: JSX.Element
  title?: string
  showHeader?: boolean
  showFooter?: boolean
  Tools?: JSX.Element
  loginRequired?: boolean
}

export function AppLayout({
  children,
  title,
  showHeader = true,
  showFooter = true,
  Tools,
  loginRequired = true,
}: Props) {
  useTheme()
  const router = useRouter()
  const auth = useAuth()

  useEffect(() => {
    if (loginRequired && !auth?.user) {
      router.push('/')
    }
  }, [auth?.user, loginRequired, router])

  return (
    <Layout>
      <GlobalStyles />

      <Head>
        <title>{`Kukkubukku${title}`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {showHeader && <Header>{Tools && <Tools />}</Header>}

      <Main showHeader={showHeader} showFooter={showFooter}>
        {children}
      </Main>

      {showFooter && <Footer />}
    </Layout>
  )
}
