// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-nocheck

import { Header } from '../Header'
import { Footer } from '../Footer'
import { Main, Layout } from './styles'
import Head from 'next/head'
import { GlobalStyles } from 'styles/globalStyles'
import { useTheme } from 'utils/hooks/useTheme'

interface Props {
  children: JSX.Element
  title?: string
  showHeader?: boolean
  showFooter?: boolean
  Tools?: JSX.Element
}

export function AppLayout({ children, title, showHeader = true, showFooter = true, Tools }: Props) {
  useTheme()

  return (
    <Layout>
      <GlobalStyles />

      <Head>
        <title>{`Kukkubukku${title}`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {showHeader && <Header>{Tools && <Tools />}</Header>}

      <Main showHeader={showHeader} showFooter={showFooter}>
        {children}
      </Main>

      {showFooter && <Footer />}
    </Layout>
  )
}
