// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-nocheck

import { Icon } from 'components/Icon'
import { Header } from '../Form/Header'
import { Footer } from '../Footer'
import { Main, Layout } from './styles'
import Head from 'next/head'
import { GlobalStyles } from 'styles/globalStyles'
import { useTheme } from 'utils/hooks/useTheme'
import Link from 'next/link'
import { MyLink } from 'components/MyLink'

interface Props {
  children: JSX.Element,
  title?: string,
}

export function AppLayout ({ children, title }: Props) {
  useTheme()

  return (
    <Layout>
      <GlobalStyles />

      <Head>
        <title>{`Kukkubukku${title}`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header>
        <Link href="/create/recipe" passHref legacyBehavior>
          <MyLink>
            <Icon
              type={Icon.TYPE.PLUS}
              size={24}
              fillColor='--kkbk--color--text--primary'
            />
          </MyLink>
        </Link>

        <Link href="/" passHref legacyBehavior>
          <MyLink>
            <Icon
              type={Icon.TYPE.MAGNIFIER}
              size={24}
              fillColor='--kkbk--color--text--primary'
            />
          </MyLink>
        </Link>
      </Header>
      <Main>{children}</Main>
      <Footer />
    </Layout>
  )
}
