export const TABLE_NAMES = {
  CALENDAR: 'Calendar',
  CALENDAR_EVENT: 'CalendarEvent',
  INGREDIENT: 'Ingredient',
  MEASUREMENT: 'Measurement',
  PLANNNING: 'Planning',
  PLANNNING_EVENT: 'PlanningEvent',
  RATING: 'Rating',
  RECIPE: 'Recipe',
  RECIPE_INGREDIENT: 'RecipeIngredient',
  RECIPE_STEP: 'RecipeStep',
  SHOPPING_LIST: 'ShoppingList',
  SHOPPING_LIST_ITEM: 'ShoppingListItem',
  TAG: 'Tag',
  USER: 'User',
}
