export const iconTypes = {
  ADD_CALENDAR: 'addCalendar',
  ADD_RECIPE: 'addRecipe',
  ALERT: 'alert',
  CALENDAR: 'calendar',
  CHECK: 'check',
  CLOCK: 'clock',
  CROSS: 'cross',
  HOME: 'home',
  LEFT_ARROW: 'left_arrow',
  MAGNIFIER: 'magnifier',
  MOON: 'moon',
  PERSON: 'person',
  PLUS: 'plus',
  RECIPES: 'recipes',
  RIGHT_ARROW: 'right_arrow',
  SAVE: 'save',
  SHARE: 'share',
  SHOPPING_LIST: 'shoppingList',
  STAR: 'star',
  SUN: 'sun',
}
